config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :models
  root to: "home#index"
  get 'push', to: 'push#index'
  post 'push/send_go', to: 'push#send_go'
  get 'push/save_phone', to: 'push#save_phone'
  post 'push/phone_install',to: 'push#phone_install'
  get 'down_andorid_app', to: 'app_down#down_andorid_app'
  post "users/create_user", to: 'users#create_user'
  get 'users/new', to: 'users#new'

  get 'users/show', to: 'users#show'
  get 'users/destroy', to: 'users#destroy'
  get 'users/update', to: "users#update"
  patch 'users/update_save', to: "users#update_save"
  get 'push/search', to: 'push#search'

end

app/models/avos.rb
class Avos < ActiveRecord::Base
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  rolify
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	def index
		@user = User.new
	end
end

app/controllers/app_down_controller.rb
class AppDownController < ApplicationController
	def down_andorid_app
		send_file '/var/www/PushDemo-debug.apk'
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    def admin_only
      if current_user
        @name = current_user.email
        unless current_user.has_role? :admin
          render :text => "你的权限不够！！！"
          @_request.reset_session
        end
      else
        redirect_to '/users/sign_in'
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :admin_only
	def index
		
	end
end

app/controllers/push_controller.rb
class PushController < ApplicationController
  before_filter :admin_only
  def index
    @users = User.all
  end
  def send_go
    userId = params[:user]
    par = params[:message]
    title = params[:title]
    begin
      res = RestClient.post 'http://139.129.49.111:81/push',{ 'message' => par,'userId' => userId,'title' => title }
      flash['notice'] = "success"
    rescue Exception => e
      ErrorMailer.error_maile(e,res).deliver
      flash['notice'] = JSON.parse(res)['type'] 
    end
    redirect_to push_path
  end
  def save_phone
    @avos = Avos.new
    @users = User.all
  end
  def phone_install
    phone_name = params[:phone_name]
    phone_install = params[:phone_install]
    @avos = Avos.new
    @avos.name = phone_name
    @avos.installation = phone_install
    @avos.user_id = params[:user]
    begin
      @avos.save
      flash[:notice] = "success"
    rescue Exception => e
      flash[:notice] = "error"
      ErrorMailer.error_maile(e,nil).deliver
    end
    redirect_to push_save_phone_path
  end

  def down_andorid_app
    send_file '/var/www/PushDemo-debug.apk'
  end
  def search
    @avos = Avos.all
  end


  def user_create
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :admin_only
  def new
    @user = User.new
  end
  def create_user
    @user = User.create(user_par)
    if @user
      flash['notice'] = 'success'
    else
      flash['notice'] = 'error'
    end
    redirect_to users_show_path
  end
  def show
    page = params[:page].present? ? params[:page] : 1 
    @users = User.all.order("id asc").paginate(page: page,per_page: 1)
  end
  def destroy
    p params[:id]
    user = User.find params[:id]
    user.destroy
    redirect_to users_show_path
  end

  def update
    @user = User.find params[:id]
  end

  def update_save
    new_user = Hash.new
    new_user['name'] = params[:user][:name] if params[:user][:name].present?
    new_user['email'] = params[:user][:email] if params[:user][:email].present?
    new_user['password'] = params[:user][:password] if params[:user][:password].present?
    begin
      @user = User.update_all(new_user)
      flash['notice'] = 'success'
    rescue Exception => e
      flash['notice'] = e.inspect
    end
    redirect_to users_show_path
  end

  private
  def user_par
    params.require(:user).permit(:email, :password, :name)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/app_down_helper.rb
module AppDownHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/push_helper.rb
module PushHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
  <div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">添加用户</h1>
  </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          添加用户
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-lg-6">
              <%=form_for(@user) do |f|%>
              
                <div class="form-group">
                  <!-- <label>选择用户：</label> --> 
                  

                  <label>输入手机信息</label>
                  <%= f.text_field :name,class: "form-control",placeholder: "用户名"%>
                  <%= f.email_field :email,class: "form-control",placeholder: "邮件"%>
                  <%= f.text_field :password,class: "form-control",placeholder: "请输入密码" %>
                  <%= f.text_field :password,class: "form-control",placeholder: "确认密码" %>
                  
                </div>
                <%= f.submit "保存",class: "btn btn-default" %>
                <button type="reset" class="btn btn-default">重置</button>
              <% end %>
              <!-- </form> -->

app/views/admin/users/index.html.erb
<%=render "form"%>

app/views/layouts/_header.html.erb
<div id="wrapper">
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.html">宋健的推送系统</a>
      </div>
      <!-- /.navbar-header -->

      <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
          </a>
          <ul class="dropdown-menu dropdown-messages">
            <li>
              <a href="#">
                <div>
                  <strong>John Smith</strong>
                  <span class="pull-right text-muted">
                    <em>Yesterday</em>
                  </span>
                </div>
                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="#">
                <div>
                  <strong>John Smith</strong>
                  <span class="pull-right text-muted">
                    <em>Yesterday</em>
                  </span>
                </div>
                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="#">
                <div>
                  <strong>John Smith</strong>
                  <span class="pull-right text-muted">
                    <em>Yesterday</em>
                  </span>
                </div>
                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a class="text-center" href="#">
                <strong>Read All Messages</strong>
                <i class="fa fa-angle-right"></i>
              </a>
            </li>
          </ul>
          <!-- /.dropdown-messages -->
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-tasks fa-fw"></i>  <i class="fa fa-caret-down"></i>
          </a>
          <ul class="dropdown-menu dropdown-tasks">
            <li>
              <a href="#">
                <div>
                  <p>
                    <strong>Task 1</strong>
                    <span class="pull-right text-muted">40% Complete</span>
                  </p>
                  <div class="progress progress-striped active">
                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                      <span class="sr-only">40% Complete (success)</span>
                    </div>
                  </div>
                </div>
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="#">
                <div>
                  <p>
                    <strong>Task 2</strong>
                    <span class="pull-right text-muted">20% Complete</span>
                  </p>
                  <div class="progress progress-striped active">
                    <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                      <span class="sr-only">20% Complete</span>
                    </div>
                  </div>
                </div>
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="#">
                <div>
                  <p>
                    <strong>Task 3</strong>
                    <span class="pull-right text-muted">60% Complete</span>
                  </p>
                  <div class="progress progress-striped active">
                    <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                      <span class="sr-only">60% Complete (warning)</span>
                    </div>
                  </div>
                </div>
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="#">
                <div>
                  <p>
                    <strong>Task 4</strong>
                    <span class="pull-right text-muted">80% Complete</span>
                  </p>
                  <div class="progress progress-striped active">
                    <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                      <span class="sr-only">80% Complete (danger)</span>
                    </div>
                  </div>
                </div>
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a class="text-center" href="#">
                <strong>See All Tasks</strong>
                <i class="fa fa-angle-right"></i>
              </a>
            </li>
          </ul>
          <!-- /.dropdown-tasks -->
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
          </a>
          <ul class="dropdown-menu dropdown-alerts">
            <li>
              <a href="#">
                <div>
                  <i class="fa fa-comment fa-fw"></i> New Comment
                  <span class="pull-right text-muted small">4 minutes ago</span>
                </div>
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="#">
                <div>
                  <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                  <span class="pull-right text-muted small">12 minutes ago</span>
                </div>
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="#">
                <div>
                  <i class="fa fa-envelope fa-fw"></i> Message Sent
                  <span class="pull-right text-muted small">4 minutes ago</span>
                </div>
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="#">
                <div>
                  <i class="fa fa-tasks fa-fw"></i> New Task
                  <span class="pull-right text-muted small">4 minutes ago</span>
                </div>
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="#">
                <div>
                  <i class="fa fa-upload fa-fw"></i> Server Rebooted
                  <span class="pull-right text-muted small">4 minutes ago</span>
                </div>
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a class="text-center" href="#">
                <strong>See All Alerts</strong>
                <i class="fa fa-angle-right"></i>
              </a>
            </li>
          </ul>
          <!-- /.dropdown-alerts -->
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
          </a>
          <ul class="dropdown-menu dropdown-user">
            <li><a href="#"><i class="fa fa-user fa-fw"></i><%=current_user.name%></a>
            </li>
            <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
            </li>
            <li class="divider"></li>
            <li>
            <%= link_to destroy_user_session_path, :method => 'delete' do %>
            <i class="fa fa-sign-out fa-fw"></i> Logout
            <%end%>
            </li>
          </ul>
          <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
      </ul>

app/views/layouts/_message.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <li><%= msg %></li>
        </div>
    <% else %>
        <% msg.each do |k, v| %>
            <% if v.present? %>
                <% v.each do |m| %>
                    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
                      <a class="close" data-dismiss="alert">&#215;</a>
                      <li><%= m %></li>
                <% end %>
                </div>
            <% end %>
        <% end %>
    <% end %>
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <!-- <li>
                            <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li> -->
                        <li>

                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i>功能<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <%=link_to '存入手机型号', push_save_phone_path%>
                                    <!-- <a href="flot.html"></a> -->
                                </li>
                                <li>
                                    <%=link_to '推送', push_path%>
                                </li>
                                <li>
                                    <%= link_to '用户管理', users_show_path %>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>PushWeb</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%#= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <% if user_signed_in? %>

		<%= render "layouts/header"%>
    <%= render "layouts/sidebar"%>
    <div id="page-wrapper">
    <%= render "layouts/message"%>
	  
    
      <%= yield %>
    <%= render "layouts/footer" %>
                 </div>
                                <!-- /.col-lg-6 (nested) -->
                                
                                <!-- /.col-lg-6 (nested) -->
                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
  <%else%>
  <%= yield %>
  <%end%>

</body>
<%= javascript_include_tag "application" %>
<script>
    $.ajaxSetup({
        headers: {
            'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        }
    });
</script>


<%= content_for?(:afterBody) ? yield(:afterBody) : '' %>

</html>

app/views/push/index.html.erb
<!-- <div id="page-wrapper"> -->

  <div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">发送控制台</h1>
  </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          发送消息
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-lg-6">
              <%= form_tag('push/send_go', multipart: true)%>
              <%#=form_for @devises,as: :post,url:push_send_go_path do |devise| %>
                <div class="form-group">
                  <label>选择用户名</label>
                    <%= select_tag "user", options_from_collection_for_select(@users, "id", "name", "1"),class: "form-control" %>

                  </br>
                  <label>输入消息体</label>
                  <input class="form-control" placeholder="Enter title" name= "title">
                  <input class="form-control" placeholder="Enter text" name= "message">
                  
                </div>
                <button type="submit" class="btn btn-default">发送</button>
                <button type="reset" class="btn btn-default">重置</button>
              </form>
              <%#end%>

app/views/push/save_phone.html.erb
  <div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">绑定手机</h1>
  </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          绑定手机
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-lg-6">
              <%=form_for @avos, url: push_phone_install_path do |f|%>
              <%#= form_tag('/push/phone_install', multipart: true)%>
                <div class="form-group">
                  <label>选择用户：</label> 
                  <%= select_tag "user", options_from_collection_for_select(@users, "id", "name", "1"),class: "form-control" %>

                  <label>输入手机信息</label>
                  <input class="form-control" placeholder="手机名称" name= "phone_name">
                  <input class="form-control" placeholder="手机安装信息" name= "phone_install">
                </div>
                <button type="submit" class="btn btn-default">保存</button>
                <button type="reset" class="btn btn-default">重置</button>
              <% end %>
              <!-- </form> -->

app/views/push/search.html.erb
  <div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">查询</h1>
  </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">        
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-lg-6">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button"><i class="fa fa-search"></i>
                </button>
              </span>

app/views/push/user_new.html.erb
user_new.html.erb

app/views/users/_form.html.erb
  <div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">添加用户</h1>
  </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          添加用户
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-lg-6">
              <% if @user.name.present? %>
                <% url = users_update_save_path %>
              <%else%>
                <% url = users_create_user_path %>
              <%end%>
              <%=form_for @user, url: url do |f|%>
              
                <div class="form-group">
                  <label>输入手机信息</label>
                  <%= f.text_field :name,class: "form-control",placeholder: "用户名"%>
                  <%= f.email_field :email,class: "form-control",placeholder: "邮件"%>
                  <%= f.password_field :password,class: "form-control",placeholder: "请输入密码" %>
                  <%= f.password_field :comfirm_password,class: "form-control",placeholder: "确认密码" %>
                  
                </div>
                <%= f.submit "保存",class: "btn btn-default",id: "sub" %>
                <button type="reset" class="btn btn-default">重置</button>
              <% end %>
<% content_for :afterBody do %>
  <script type="text/javascript">
    $(function() {
      $("#sub").bind("click",function(event){
        var password = $("#user_password").val()
        var comfirm_password = $("#user_comfirm_password").val()
        if (password!=comfirm_password) {
          alert("2次密码不一样")
          return false
        }  
      })
    });
    
  </script>
<%end%>

app/views/users/new.html.erb
<%=render "form"%>

app/views/users/show.html.erb
  <div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">用户管理</h1>
  </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          用户管理
        </div>      
      <div class="panel-body">
        <div class="dataTable_wrapper">
          <table class="table table-striped table-bordered table-hover" id="user-faces-table">
            <thead>
            <tr>
              <th>用户ID</th>
              <th>用户名称</th>
              <th>用户邮箱</th>
              <th>操作</th>
            </tr>
            </thead>
            <tbody>
            <% @users.each do |ad| %>
                <tr class="odd gradeX">
                  <td><%= ad.id %></td>
                  <td><%= ad.name %></td>
                  <td><%= ad.email%></td>
                  <td>
                  <%=link_to "删除", users_destroy_path(id: ad.id),class: "btn btn-outline btn-primary"%>
                  <%=link_to "更新", users_update_path(id: ad.id),class: "btn btn-outline btn-primary"%>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
          <%= link_to "添加用户", users_new_path,class: "btn btn-primary" %>
          <!-- <botton class="btn btn-primary">mmm</botton> -->
          <%= will_paginate @users %>

app/views/users/update.html.erb
<%=render "form"%>